[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Vary = "Accept-Encoding"
    Server = "Go"
