[[headers]]
  for = "/news/*"
  [headers.values]
    Cache-Control = '''
      no-store,
      must-revalidate'''
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = '''
      public,
      max-age=31536000,
      immutable'''
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[build]
  command = "pnpm run build"
  publish = "dist"
