backend:
    name: git-gateway
    branch: main
    login: true
    roles: ['admin']
media_folder: 'src/assets'
public_folder: 'src/assets'
site_url: 'https://mdg-agency.com/'
locale: 'vi'
show_preview_links: true
description: 'Danh sách bài viết'
slug:
    encoding: 'ascii'
    clean_accents: true
    sanitize_replacement: '-'
logo_url: 'https://github.com/ovftank.png'
collections:
    - name: 'bai-viet'
      locale: 'vi'
      label: 'Bài viết'
      folder: 'src/content/bai-viet'
      create: true
      slug: '{{slug}}'
      fields:
          - {
                label: 'Tiêu đề',
                name: 'title',
                widget: 'string',
                required: true
            }
          - {
                label: 'Mô tả',
                name: 'description',
                widget: 'text',
                required: true,
                pattern:
                    ['^.{50,160}$', 'Must be between 50 and 160 characters'],
                hint: 'Mô tả ngắn gọn từ 50-160 ký tự để tối ưu SEO'
            }
          - { label: 'Ảnh OG', name: 'thumbnail', widget: 'image' }
          - {
                label: 'Ngày đăng',
                name: 'date',
                widget: 'datetime',
                format: 'YYYY-MM-DD HH:mm',
                date_format: 'DD/MM/YYYY',
                time_format: 'HH:mm',
                required: true,
                default: '{{now}}'
            }
          - {
                label: 'Danh mục',
                name: 'category',
                widget: 'select',
                options:
                    [
                        'facebook',
                        'tiktok',
                        'youtube',
                        'instagram',
                        'content-writer',
                        'other'
                    ],
                default: 'other'
            }
          - {
                label: 'Thời gian đọc',
                name: 'readTime',
                widget: 'string',
                default: '5 min read'
            }
          - { label: 'Nội dung', name: 'body', widget: 'markdown' }
